version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
